# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import openCurrents.models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pop_image',
            field=models.ImageField(max_length=512, null=True, upload_to=openCurrents.models.path_and_rename),
        ),
    ]
