# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0002_token_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
