# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0003_usercashout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
