# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-21 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0004_ledger_is_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='cashout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.UserCashOut'),
        ),
        migrations.AddField(
            model_name='usercashout',
            name='status',
            field=models.CharField(choices=[('req', 'requested'), ('prc', 'processed'), ('red', 'redeemed')], default='req', max_length=7),
        ),
        migrations.AddField(
            model_name='usercashout',
            name='system',
            field=models.CharField(choices=[('dwl', 'Dwolla'), ('ppl', 'Paypal')], default='ppl', max_length=7),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.AdminActionUserTime'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.TransactionAction'),
        ),
        migrations.AlterField(
            model_name='org',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='intro',
            field=models.CharField(blank=True, max_length=16192, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pop_no_proof',
            field=models.CharField(blank=True, max_length=8096, null=True),
        ),
    ]
