# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0005_auto_20170303_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
