# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openCurrents.models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0005_auto_20180521_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to=openCurrents.models.path_and_rename_giftcard)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('gft', 'giftcard'), ('cbk', 'cashback')], default='cbk', max_length=4),
        ),
        migrations.AddField(
            model_name='giftcardinventory',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Offer'),
        ),
        migrations.AddField(
            model_name='transactionaction',
            name='giftcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.GiftCardInventory'),
        ),
    ]
