# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0006_auto_20170303_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orguser',
            unique_together=set([('user', 'org')]),
        ),
    ]
