# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-10 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0007_offer_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='is_featured_master_biz',
            field=models.BooleanField(default=False),
        ),
    ]
