# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0007_auto_20170303_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='website',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
