# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0009_remove_org_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='affiliation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
