# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0009_org_is_featured_master_biz_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
