# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0010_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
