# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0010_auto_20170428_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
