# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-10 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0011_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
