# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-22 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0012_auto_20170521_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereventregistration',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.RenameField(
            model_name='usertimelog',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
