# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-25 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import openCurrents.models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0013_auto_20180810_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='logo',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=openCurrents.models.path_and_rename_org_logo),
        ),
    ]
