# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0013_auto_20170522_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinator_email',
            field=models.EmailField(default='coordinator@oc.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='coordinator_firstname',
            field=models.CharField(default='firstname', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='desc', max_length=8192),
            preserve_default=False,
        ),
    ]
