# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0014_auto_20170522_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='default', max_length=1024),
            preserve_default=False,
        ),
    ]
