# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 23:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0015_auto_20170522_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usereventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='usereventregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertimelog',
            name='event',
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 23, 2, 16, 362746), verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 23, 2, 21, 746517), verbose_name='start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertimelog',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='UserEventRegistration',
        ),
        migrations.AddField(
            model_name='userprojectregistration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Project'),
        ),
        migrations.AddField(
            model_name='userprojectregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
