# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0016_auto_20170524_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_start',
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 4, 17, 39, 873753), verbose_name='end datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 4, 17, 44, 33565), verbose_name='start datetime'),
            preserve_default=False,
        ),
    ]
