# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0017_auto_20170525_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=8192)),
                ('location', models.CharField(max_length=1024)),
                ('coordinator_firstname', models.CharField(max_length=128)),
                ('coordinator_email', models.EmailField(max_length=254)),
                ('datetime_start', models.DateTimeField(verbose_name='start datetime')),
                ('datetime_end', models.DateTimeField(verbose_name='end datetime')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='coordinator_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='coordinator_firstname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='datetime_start',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Project'),
        ),
    ]
