# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0018_auto_20170529_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprojectregistration',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojectregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProjectRegistration',
        ),
    ]
