# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0020_auto_20170601_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertimelog',
            old_name='date_end',
            new_name='datetime_end',
        ),
        migrations.RenameField(
            model_name='usertimelog',
            old_name='date_start',
            new_name='datetime_start',
        ),
    ]
