# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0021_auto_20170601_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertimelog',
            options={'get_latest_by': 'datetime_start'},
        ),
    ]
