# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0022_auto_20170601_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='timezone',
            field=models.CharField(default='America/Chicago', max_length=128),
        ),
    ]
