# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0024_account_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
    ]
