# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0025_auto_20170607_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'datetime_start', 'ordering': ['datetime_start']},
        ),
    ]
