# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0026_auto_20170610_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MN', 'ManualTracking'), ('GR', 'Group'), ('OT', 'Other')], default='GR', max_length=2),
        ),
    ]
