# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0026_auto_20170610_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'get_latest_by': 'date_created'},
        ),
    ]
