# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0027_auto_20170712_1959'),
        ('openCurrents', '0027_auto_20170711_2158'),
    ]

    operations = [
    ]
