# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0027_auto_20170720_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
