# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0027_auto_20170720_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
