# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0027_account_monthy_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='monthy_updates',
            new_name='monthly_updates',
        ),
    ]
