# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0028_merge_20170719_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MN', 'ManualTracking'), ('GR', 'Group')], default='GR', max_length=2),
        ),
    ]
