# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0028_auto_20170721_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
