# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0029_auto_20170724_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertimelog',
            name='datetime_duration',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
