# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0031_auto_20170725_1939'),
        ('openCurrents', '0028_account_monthly_updates'),
    ]

    operations = [
    ]
