# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0032_merge_20170726_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertimelog',
            name='datetime_duration',
        ),
    ]
