# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0033_remove_usertimelog_datetime_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
