# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0033_remove_usertimelog_datetime_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orguser',
            options={'permissions': (('admin', 'User is org admin'),)},
        ),
        migrations.AddField(
            model_name='orguser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='org',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
