# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0033_remove_usertimelog_datetime_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredUserTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='org',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deferredusertime',
            name='usertimelog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.UserTimeLog'),
        ),
        migrations.AddField(
            model_name='usertimelog',
            name='deferments',
            field=models.ManyToManyField(related_name='deferments', through='openCurrents.DeferredUserTime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deferredusertime',
            unique_together=set([('user', 'usertimelog')]),
        ),
    ]
