# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0035_auto_20170803_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notified',
        ),
    ]
