# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0037_auto_20170807_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notified',
        ),
    ]
