# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0039_auto_20170808_0547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deferredusertime',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='deferredusertime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deferredusertime',
            name='usertimelog',
        ),
        migrations.AlterModelOptions(
            name='orguser',
            options={'permissions': (('admin', 'User is org admin'),)},
        ),
        migrations.RemoveField(
            model_name='usertimelog',
            name='deferments',
        ),
        migrations.AddField(
            model_name='orguser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DeferredUserTime',
        ),
    ]
