# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0040_auto_20170808_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='orguser',
            name='approved',
        ),
        migrations.AddField(
            model_name='event',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
