# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-09 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0042_auto_20170809_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredUserTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertimelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.UserTimeLog')),
            ],
        ),
        migrations.AddField(
            model_name='usertimelog',
            name='deferments',
            field=models.ManyToManyField(related_name='deferments', through='openCurrents.DeferredUserTime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deferredusertime',
            unique_together=set([('user', 'usertimelog')]),
        ),
    ]
