# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0044_auto_20170815_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='orguser',
            name='approved',
        ),
    ]
