# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0045_auto_20170815_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
