# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0047_auto_20170818_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionUserTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('app', 'approved'), ('def', 'deferred'), ('dec', 'declined')], max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deferredusertime',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='deferredusertime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deferredusertime',
            name='usertimelog',
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='deferments',
            field=models.ManyToManyField(related_name='deferments', through='openCurrents.AdminActionUserTime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeferredUserTime',
        ),
        migrations.AddField(
            model_name='adminactionusertime',
            name='usertimelog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.UserTimeLog'),
        ),
        migrations.AlterUniqueTogether(
            name='adminactionusertime',
            unique_together=set([('action_type', 'user', 'usertimelog')]),
        ),
    ]
