# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0050_auto_20170824_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionusertime',
            options={'get_latest_by': 'datetime_start'},
        ),
    ]
