# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0051_auto_20170830_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionusertime',
            options={},
        ),
    ]
