# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0052_auto_20170830_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currents_share', models.DecimalField(decimal_places=2, max_digits=3)),
                ('limit', models.IntegerField(default=-1)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Item')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Org')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_image', models.ImageField(upload_to=b'')),
                ('pop_type', models.CharField(choices=[('rec', 'receipt'), ('oth', 'other')], default='rec', max_length=3)),
                ('price_reported', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='UserOfferAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('req', 'requested'), ('app', 'approved'), ('red', 'redeemed')], default='req', max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Offer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.ManyToManyField(through='openCurrents.UserOfferAction', to='openCurrents.Offer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
