# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0053_auto_20170920_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='mission',
        ),
    ]
