# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0053_auto_20170920_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currents_share',
            field=models.IntegerField(),
        ),
    ]
