# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0054_auto_20171004_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pop_image',
            field=models.ImageField(upload_to='redeem/%Y/%m/%d'),
        ),
    ]
