# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0056_auto_20171012_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userofferaction',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='offer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Offer'),
            preserve_default=False,
        ),
    ]
