# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0059_auto_20171016_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='org',
            name='reason',
        ),
        migrations.AlterField(
            model_name='org',
            name='status',
            field=models.CharField(choices=[('biz', 'business'), ('npf', 'non-profit')], default='npf', max_length=3),
        ),
    ]
