# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0060_auto_20171017_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='cr_available',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='pending',
            new_name='cr_pending',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='fiat_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='fiat_pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BizEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openCurrents.Entity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Org')),
            ],
            bases=('openCurrents.entity',),
        ),
        migrations.CreateModel(
            name='OrgEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openCurrents.Entity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Org')),
            ],
            bases=('openCurrents.entity',),
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openCurrents.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('openCurrents.entity',),
        ),
        migrations.AddField(
            model_name='entity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_entity', to='openCurrents.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_entity', to='openCurrents.Entity'),
        ),
    ]
