# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0061_auto_20171022_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('cur', 'current'), ('usd', 'dollar')], default='cur', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_out', to='openCurrents.Account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_in', to='openCurrents.Account')),
            ],
        ),
    ]
