# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0063_auto_20171023_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizentity',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Org'),
        ),
        migrations.AlterField(
            model_name='orgentity',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openCurrents.Org'),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
