# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0061_auto_20171103_0741'),
        ('openCurrents', '0064_auto_20171023_0536'),
    ]

    operations = [
    ]
