# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openCurrents', '0065_merge_20171107_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/Chicago', max_length=128)),
                ('monthly_updates', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='bizentity',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='bizentity',
            name='org',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='BizEntity',
        ),
    ]
