# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0068_auto_20171111_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
