# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0070_auto_20171117_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='action',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.AdminActionUserTime'),
            preserve_default=False,
        ),
    ]
