# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0072_auto_20171117_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openCurrents.TransactionAction'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionaction',
            unique_together=set([('transaction', 'action_type')]),
        ),
    ]
