# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0073_auto_20171126_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionusertime',
            name='action_type',
            field=models.CharField(choices=[('app', 'approved'), ('dec', 'declined'), ('req', 'approval_request')], max_length=3),
        ),
    ]
