# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0074_auto_20171126_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionaction',
            options={'get_latest_by': 'date_updated'},
        ),
        migrations.AddField(
            model_name='org',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='intro',
            field=models.CharField(max_length=16192, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
