# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0074_auto_20171126_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionaction',
            options={'get_latest_by': 'date_updated'},
        ),
        migrations.AddField(
            model_name='usersettings',
            name='popup_reaction',
            field=models.NullBooleanField(default=None),
        ),
    ]
