# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0075_auto_20171208_0217'),
        ('openCurrents', '0075_auto_20171205_1157'),
    ]

    operations = [
    ]
