# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0077_auto_20171227_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
