# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openCurrents', '0079_offer_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='biz_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
